### ISSUE TITLE
What happens when Apple removes OpenGL from its macOS?

### ISSUE THREAD

**Issue by mithrendal** [FrodeSolheim/fs-uae#181]
I learned that fsuae does its drawings through  SDL2, which currently depends on OpenGL right?

Recently Apple announced deprecation of OpenGL in their future OS Versions. They want the adoption of their  metal. 

So that made me I think that  old versions of fsuae will stop working some day in the future.

I have also read in the web that the SDL team added a Metal 2D render implementation in SDL 2.0.8 onwards. 
Can this be used in fsuae as well ?

**Comment by FrodeSolheim** [comment]
Hi, yes, FS-UAE uses SDL2 but also OpenGL directly. So a new Metal renderer cannot be used directly.

If Apple drops OpenGL at some point, it is likely that I'll write a generic SDL2 backend for FS-UAE, so that FS-UAE can use anything supported by SDL2 (including the Metal implementation you're referring to).

So no reason to worry :)

(But I'm still quite annoyed that Apple deprecated OpenGL...)
