### ISSUE TITLE
[Question] Is FS-UAE still being developed?

### ISSUE THREAD

**Issue by QkiZMR** [FrodeSolheim/fs-uae#193]
There's no development since 2015.

**Comment by FrodeSolheim** [comment]
Yes. but somewhat slow (PS: The latest commit in this repo is from August 2018).

**Comment by QkiZMR** [comment]
Do you plan to import more features from WinUAE? Like emulating Amiga LEDs with keyboard LEDs.

**Comment by Gagert** [comment]
I prefer fs-uae to winuae, mainly because of the native xinput-support, whdload-support and the fancy interface that can be accessed while running an Amiga application. In my opinion that makes fs-uae more fit to a htpc-setup than winuae.

However, I sorely miss the ability to choose the games refresh rate in the config files itself. Much of the library of the Amiga was for PAL systems thereby 50hz. My current solution to this as of now is to run a free third-party app that changes the screens refresh rate to 50hz before starting fs-uae automatically, and after I close fs-uae returns the screen refresh rate to its highest supported value.

**Comment by FrodeSolheim** [comment]
Keyboard LEDs are difficult to do cross-platform. Many environments do not let user application control these. So that's not likely.

Changing resolution, perhaps. That's also somewhat tricky to reliably cross-platform, in some cases you must also switch resolution. But maybe a simple feature to switch between 50 and 60 Hz in the simple cases where the desktop resolution is available in both 50/60 Hz.
