### ISSUE TITLE
XZ files do not work

### ISSUE THREAD

**Issue by moubctez** [FrodeSolheim/fs-uae#212]
In FS-UAE Launcher 3.0.0, adding .adf.xz files as floopy images does not work; .adf.gz work correctly, but my guess is, these are handled by FS-UAE itself.
Quick check in **fsgs/archive.py**: `get_handler()` is never called.
Please, investigate.

**Comment by borb** [comment]
I think this needs to be raised in https://github.com/FrodeSolheim/fs-uae-launcher rather than here; also, I'm looking at several ways in which floppy images are handled in the code, and there are several ways to add floppy images: Could you identify which mechanism - e.g. direct insertion, media swap list, or within the Floppies subdirectory and scanned by the file database scanner?

**Comment by FrodeSolheim** [comment]
This was added to fs-uae-launcher in version 2.9.11dev :)
