### ISSUE TITLE
FTBFS with gcc-11

### ISSUE THREAD

**Issue by musuruan** [FrodeSolheim/fs-uae#253]
fs-uae 3.0.5 cannot be compiled with gcc-11. Tested on Fedora 34.

There are many "error: ISO C++17 does not allow dynamic exception specifications"

Please see the following build log:
https://koji.rpmfusion.org/kojifiles/work/tasks/239/460239/build.log

**Comment by FrodeSolheim** [comment]
Have you tried compiling with an earlier C++ standard, for example using `-std=c++14` as a workaround?

**Comment by musuruan** [comment]
If I force `-std=c++14` it will avoid the C++17 errors but gcc will hit others later.

Build log attached.
[build.log](https://github.com/FrodeSolheim/fs-uae/files/6148058/build.log)

**Comment by FrodeSolheim** [comment]
I think you can "fix" the new issues by adding `-fpermissive`. Alternatively, maybe `-std=gnu++14` is less strict also.

Note: I think most/all these issues arise from C code from other projects being included into WinUAE (and FS-UAE) and reclassified as C++ in the process, since the C (not C++) compiler in Visual Studio has traditionally - and possibly still - been shitty. I might have to deal with these issues properly later, but for now, lets just use compiler flags to make it work...

**Comment by musuruan** [comment]
I could successfully built fs-uae with `-std=gnu++14 -fpermissive`.

Build log:
https://koji.rpmfusion.org/kojifiles/work/tasks/5365/475365/build.log

**Comment by glaubitz** [comment]
If you make a new minor release with the patch included, I can update the Debian package later today.
