### ISSUE TITLE
M1 "Keystroke Receiving" Issue. 

### ISSUE THREAD

**Issue by danielktdoranie** [FrodeSolheim/fs-uae#259]
So I am running the native build of FS-UAE on my MacBook Air (M1, 2020) on macOS Big Sur 11.4 (20F71). 

When I open FS-UAE Launcher I am prompted to grant FS-UAE Launcher access in System Preferences,  "Keystroke Receiving" . I have granted this but I am still prompted every time I open FS-UAE Launcher, even though I have a blue checkmark next to FS-UAE Launcher. 

See attached screenshots.
<img width="1440" alt="Screenshot 2021-06-22 at 16 16 37" src="https://user-images.githubusercontent.com/69985694/122952352-e6198a80-d375-11eb-89e5-c9776abbf2d3.png">
<img width="1440" alt="Screenshot 2021-06-22 at 16 16 52" src="https://user-images.githubusercontent.com/69985694/122952425-ef0a5c00-d375-11eb-9b3b-4c12180351e7.png">

**Comment by FrodeSolheim** [comment]
I have figured out what causes the warning; it's because the launcher runs fs-uae-device-helper (from FS-UAE.app) in order to detect mouse devices (apparently, this uses low-level APIs that macOS now warns about). I don't know why the warning would re-appear every time though....

One possible solution is to only look for multiple mouse devices if the user enables an option for this in FS-UAE Launcher settings. It is after all a very seldom used feature (multiplayer Lemmings...).

**Comment by FrodeSolheim** [comment]
I've identifies two causes for this:
- The manymouse library
- SDL 2.0.16

Support for multiple mice on macOS has been disabled in the latest v3.1 releases because of this - at least for now.
I'm including a patch for SDL 2.0.16 (https://github.com/libsdl-org/SDL/issues/4887) which fixes the warning, and new builds of FS-UAE 3 and 4 are on the way with this patch included.

**Comment by FrodeSolheim** [comment]
Closing this as fixed. Re-enabling multiple mice functionality is scheduled for 3.2: https://github.com/FrodeSolheim/fs-uae/issues/276
