### ISSUE TITLE
Add MIDI support in FS-UAE?

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#30]
Several people have voiced interest in MIDI support in FS-UAE (http://eab.abime.net/showthread.php?t=68356). There's currently no plans for this, but you can subscribe to this issue if you want to help with it, should it be implemented in the future - or just to get notifications if anything exciting happens in this regard.

**Comment by Yaniki** [comment]
Hi Friends

I've posted the same on FSUAE forum, maybe it will be interested for you too: 

I've "discovered" FSUAE (it's impressive, I never supposed this is even possible to create such an accurate emulation) 4 days ago, so I'm very new member of the community, but - because I'm also interested in MIDI bridge between emulated Amiga and the "host" - I've done several simple experiments on that filed.

First of all: as we know, typical MIDI solution for Amiga was based on interface plugged into serial port, and most MIDI apps are just sending/receiving MIDI data to/from serial (even without checking if the MIDI interface is connected or not). So we don't need any special "MIDI functionality" inside the UAE - just an accurate Amiga serial port emulation. We also need a technique for redirecting data from the emulated serial port to the MIDI ports (hardware or virtual) on the host side.

FSUAE is already equipped with serial port emulation and we can choose "emulation mode" for serial port between (a) linking emulated serial port with any serial port (hardware or virtual) of the host or (b) using TCP socket. Everything you need to know for this is here: https://fs-uae.net/docs/serial-port

I played a bit with first "mode" (using socat to create virtual serial port), but with no success - I think, there is a problem with OSX Sierra blocking access to some resources and I was unable to establish communication between virtual serial port and my own software.

Then I used TCP/IP serial port. I sketched simple pipeline (in Java/Processing and MaxMSP) redirecting data from TCP socket to my MIDI equipment. On FSUAE side I used various versions of OctaMED (my favorite tracker) to generate MIDI messages. Early results which I have achieved are rather promising: MIDI data sent via this pipeline are corectly formatted and finally I can redirect them to "external" MIDI ports and to control MIDI equipment.

I just wanted to point out that this was very early attempt - I tested the pipeline transmitting Note On / Note Off messages only (no controllers or program change yet - however they should be very simple to handle, too) and I'm not sure if the emulated serial port on FSUAE side and TCP/IP transmission are fast and accurate enough to handle any "real world" MIDI data traffic. Also I observed some strange behaviours with OctaMED itself, but I have to investigate it deeper - anyway, that was noting very problematic.

But the basic conclusion after my tests is rather promising: generic MIDI is already supported in FSUAE.

I'm very busy with some projects right now, but I want to go back to the topic in a few weeks, maybe still in late May.

**Comment by FrodeSolheim** [comment]
MIDI support by @cnvogelg is merged into FS-UAE and will be included in the next development release :) :+1:

**Comment by Yaniki** [comment]
Great!

p

**Comment by Ral-Clan** [comment]
I am not sure what "MIDI SUPPORT" in an emulator is?  In WinUAE I was just able to get MIDI to work by doing a pass-through of the emulated (virtual) parallel or serial port output (I can't remember) to the Windows device. Is that it?

Brent Santin --- Ontario, Canada.www.brentsantin.com
 

    On Tuesday, March 3, 2020, 2:57:46 p.m. EST, Yaniki <notifications@github.com> wrote:  
 
 Great!

p

**Comment by FrodeSolheim** [comment]
@Ral-Clan Well, yes. This is about being able to pass MIDI data from emulated serial port to a host MIDI device. The host MIDI device could be a hardware output, or a virtual MIDI device. I've tested on Linux with fluidsynth and munt/mt32. Seems to work great :)

**Comment by Ral-Clan** [comment]
Well good news anyway. I always use WinUAE, and loved it in Windows. When I switched to Linux I found FS-UAE wasn't as good (not as fast and not as many featured / configurability). I even found that WinUAE worked faster under Wine in Linux that FS-UAE did natively.
Good to hear that FS-UAE is being improved. It sounds like it is worth giving another try.

Brent Santin --- Ontario, Canada.
www.brentsantin.com
 

    On Tuesday, March 3, 2020, 4:15:21 p.m. EST, Frode Solheim <notifications@github.com> wrote:  
 
 
@Ral-Clan Well, yes. This is about being able to pass MIDI data from emulated serial port to a host MIDI device. The host MIDI device could be a hardware output, or a virtual MIDI device. I've tested on Linux with fluidsynth and munt/mt32. Seems to work great :)

**Comment by HoraceAndTheSpider** [comment]
Another one here who would welcome USB midi device support (input and output) in OSX FS-UAE.... I've tried looking through some of the comments here for a solution but none that work for me. Atm, i am only looking to use a midi keyboard controller to write some notes into Octamed
