### ISSUE TITLE
Let media keys (at least for volume) work after UAE launched.

### ISSUE THREAD

**Issue by stuaxo** [FrodeSolheim/fs-uae#73]
It would be really handy, on my laptop I have to press FN to use the volume so it doesn't interfere with UAE keys anyway.

**Comment by FrodeSolheim** [comment]
@stuaxo what operating system are you using? Can you give a bit more details about the "interference"?

**Comment by stuaxo** [comment]
Ah, I just meant it shouldn't be a keycode that uae cares about.

I'm on Ubuntu 15.04 64 bit, volume fn + f10 / f11 / f12 (mute vol down  vol up)

I can probably run ex event to get the real key codes..

**Comment by FrodeSolheim** [comment]
The problem is that especially on Linux, when keyboard input grabbed, *all* keys are grabbed. I don't know of any way to specify that I want to grab all keys *except volume keys* for example.

The only "easy" option is to not grab the keyboard at all. There is an option to disable this actually, you can find it in FS-UAE Launcher settings ("Grab keyboard when input is grabbed"). You'll still get keyboard events, but not for shortcuts which are intercepted by the desktop / other apps, so some keys may then become unusable for emulation.

Another *theoretically* possible option is to:
* Recognize a set of special keys (such as volume keys) in FS-UAE
* If such a key press is detected, temporarily release input grab and inject a new fake key press and release to X11 using the XTEST extension, and then grab the input again.

**Comment by stuaxo** [comment]
I wonder if there's an api to find out which keys are the volume and mute keys ?

Then it would be possible to change the volume when they are pressed. - this is probably better than passing them through.

**Comment by stuaxo** [comment]
I'll have a go with key grab disabled for the mo and see how it goes

**Comment by FrodeSolheim** [comment]
Yes, allowing media keys to be used *with* FS-UAE is much easier than trying to hack together a pass-through workaround :)

**Comment by FrodeSolheim** [comment]
Using (volume) media keys with FS-UAE implemented in FS-UAE 2.7.3dev (out now).

**Comment by stuaxo** [comment]
Wow, awesome work ! - will give it a try.
